version: "3.7"
services:
  db:
    image: postgres
    container_name: CMS-database
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  backend:
    build:
      context: ./backend
    container_name: CMS-backend
    command: yarn start
    ports:
      - 8080:8080
    volumes:
      - ./backend/:/backend
      - backend-modules:/backend/node_modules
  frontend:
    build:
      context: ./frontend
    container_name: CMS-frontend
    command: yarn start
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/frontend
      - frontend-modules:/frontend/node_modules
volumes:
  backend-modules:
  frontend-modules:
