version: "3.7"
services:
  db:
    image: postgres
    container_name: CMS-database
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  db-migrator:
    build:
      context: ./backend
    command: sh -c "yarn db:retryable-migrate && yarn db:seed"
    depends_on:
      - db
    image: backend
  backend:
    build:
      context: ./backend
    image: backend
    container_name: CMS-backend
    command: yarn start
    depends_on:
      - db
      - db-migrator
    ports:
      - 8080:8080
    volumes:
      - ./backend/:/backend
      - backend-modules:/backend/node_modules
  frontend:
    build:
      context: ./frontend
    container_name: CMS-frontend
    command: yarn start
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/frontend
      - frontend-modules:/frontend/node_modules
volumes:
  database-data:
    driver: local
  backend-modules:
  frontend-modules:
